### PR TITLE
fix: gracefully handle comments in resolv.conf. Fixes #171

### LINKED ISSUE #171: nginx: [emerg] invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2
**Describe the bug**
Poorly constrained `grep` in the bash scripts seems to pick up a comment from the `/etc/resolv.conf` file.

**To Reproduce**
1. Start container ```docker run --env-file ./settings --publish 8011:80 --name nginx-s3-gateway nginx-s3-gateway:oss```
2. View logs
3. See error:
```
2023/09/13 11:50:22 [emerg] 1#1: invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2
nginx: [emerg] invalid IPv6 address in resolver "[NOTE:]" in /etc/nginx/conf.d/upstreams.conf:2
```

**Expected behavior**
The server starts as expected.

**Your environment**
* Local clone of the master branch at time of writing.

**Additional context**
See this line beginning with `# NOTE` and ending in `nameservers`...
```
nameserver 8.8.4.4
nameserver 94.198.184.14
nameserver 94.198.184.34
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 8.8.8.8
```
 ... it qualifies for the `grep` commands found here: https://github.com/search?q=repo%3Anginxinc%2Fnginx-s3-gateway%20%22grep%20nameserver%22&type=code
**Sensitive Information**

### PR DESCRIPTION
**Pull request by 4141done**
# What
Fixes an issue where comments in the `/etc/resolv.conf` would get into the dns resolvers list and cause an error when starting the s3 gateway.

## How
Following a suggestion on the issue, the logic from [this file](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/15-local-resolvers.envsh) in the official NGINX docker container was ported over to replace the existing logic.

Given a `/etc/resolv.conf` that looks like this:
```
nameserver 127.0.0.11
nameserver 8.8.4.4
nameserver 94.198.184.14
nameserver 94.198.184.34
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 8.8.8.8
options ndots:0

```

The existing code would produce this:
```
127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 [NOTE:] The 8.8.8.8
```

With this change applied it looks like this:
```
127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 8.8.8.8
```

The startup printout looks like this with the change applied:
```
Origin: http://bucket-1.minio:9000
Region: us-east-1
Addressing Style: virtual
AWS Signatures Version: v2
DNS Resolvers: 127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 8.8.8.8
Directory Listing Enabled: false
Directory Listing Path Prefix:
Provide Index Pages Enabled:
Append slash for directory enabled:
Stripping the following headers from responses: x-amz-;
CORS Enabled: 0
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
```

## Notes
Ideally we should be incorporating the entrypoint scripts from the official nginx docker image.  For now we're just porting key logic to get the issue solved quickly.  The integration of these scripts will have some other concerns.  An issue has been filed for this work: https://github.com/nginxinc/nginx-s3-gateway/issues/175

### CODE REVIEW

**Review by ciroque — APPROVED** [review]
I like what you've done here

File: common/docker-entrypoint.sh [hunk 1]
```diff
@@ -32,16 +32,11 @@ parseBoolean() {
...
-    else
-      resolvers="$resolvers $ip"
-    fi
-  done
-  export DNS_RESOLVERS="${resolvers}"
+   # This method of pulling individual nameservers from
+   # /etc/resolv.conf taken from the entrypoint script in the
+   # official docker image.
+   # https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/15-local-resolvers.envsh
+  export DNS_RESOLVERS="$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print $2}' /etc/resolv.conf)"
```
Comment (dekobon) [inline common/docker-entrypoint.sh:39]: Does this awk pattern support ipv6 syntax? In order to template in ipv6 ips into nginx config, they must be enclosed in `[]`. This was raised in [this bug](https://github.com/nginxinc/nginx-s3-gateway/issues/83).
The fix was [here](https://github.com/nginxinc/nginx-s3-gateway/commit/97a87377bdda5de8d61442d81514cd61ed48ee32).

**Review by dekobon — CHANGES_REQUESTED** [review]
No changes requested, rather this is a request to make sure that the new method does not cause a regression with ipv6 addresses.

File: common/docker-entrypoint.sh (hunk 1 above)
Comment (4141done) [reply common/docker-entrypoint.sh]: Thank you for catching this! I had overlooked this case and missed the enclosure in square brackets from the original code.  I've made changes in [this commit](https://github.com/nginxinc/nginx-s3-gateway/pull/176/commits/0c1d73234c387f2a47f4e2150da3ae7595b3213e) that combines your fix with the changes from the official dockerfile entrypoint.

Given a `resolv.conf` that looks like this:
```
nameserver 127.0.0.11
nameserver 8.8.4.4
nameserver 94.198.184.14
nameserver 94.198.184.34
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 8.8.8.8
# This is another comment
nameserver 8.8.8.9
nameserver fe80::f03c:93ff:fe25:6762
nameserver 8.9.9.9
nameserver 2a03:a800:2:1::1
nameserver 8.9.9.7
options ndots:0
```

We see:
```
DNS Resolvers:  127.0.0.11 8.8.4.4 94.198.184.14 94.198.184.34 8.8.8.8 8.8.8.9 [fe80::f03c:93ff:fe25:6762] 8.9.9.9 [2a03:a800:2:1::1] 8.9.9.7
```

Which looks right to me. Based on my read of the `resolver` syntax each address should be separately enclosed in square brackets.

**Review by dekobon — APPROVED** [review]
